
import javax.swing.JOptionPane;


/**
 * Crea la ventana principal de la aplicación e
 * inicializa sus componentes.
 */
public class Main extends javax.swing.JFrame {

    private GestorEntidades gestorEntidades;

    /**
    * Constructor principal de la aplicación.
    *
    * Inicializa los componentes de la interfaz
    * y carga las entidades de ejemplo.
    */
    public Main() {
        gestorEntidades = new GestorEntidades();
        gestorEntidades.cargarDatos();
        initComponents();
        actualizarCampos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPrincipal = new javax.swing.JTabbedPane();
        jPanelEmpleados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        cmbTipoEmpleado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtRegion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtIdioma = new javax.swing.JTextField();
        txtExperiencia = new javax.swing.JTextField();
        txtEmpresa = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        txtFechaContratacion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();
        jPanelVehiculo = new javax.swing.JPanel();
        btnAgregarVehiculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPatente = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        jPanelMostrarEntidades = new javax.swing.JPanel();
        txtAreaResultado = new java.awt.TextArea();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de turismo Llanquigue Tour");

        tabPrincipal.setName("Empleados"); // NOI18N
        tabPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPrincipalStateChanged(evt);
            }
        });

        jLabel2.setText("Nombre");

        btnAgregar.setText("Agregar empleado");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        cmbTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guia turistico", "Colaborador externo", "Recepcionista" }));
        cmbTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEmpleadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Rut:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("Correo electronico:");

        jLabel7.setText("Edad:");

        jLabel8.setText("Calle:");

        jLabel9.setText("Ciudad:");

        jLabel10.setText("Region:");

        jLabel11.setText("Numero:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel13.setText("Especialidad:");

        jLabel14.setText("Experiencia:");

        jLabel15.setText("Idioma:");

        jLabel16.setText("Empresa:");

        jLabel17.setText("Sueldo:");

        jLabel18.setText("Fecha contratacion:");

        txtFechaContratacion.setToolTipText("");

        jLabel19.setText("Turno:");

        txtTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmpleadosLayout = new javax.swing.GroupLayout(jPanelEmpleados);
        jPanelEmpleados.setLayout(jPanelEmpleadosLayout);
        jPanelEmpleadosLayout.setHorizontalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addComponent(cmbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                    .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addGap(23, 23, 23))
                                        .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                            .addGap(200, 200, 200)
                                            .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel19))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEmpleadosLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEmpleadosLayout.createSequentialGroup()
                                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCiudad)
                                            .addComponent(txtCalle)
                                            .addComponent(txtNombre)
                                            .addComponent(txtTelefono)
                                            .addComponent(txtCorreo)
                                            .addComponent(txtEdad)
                                            .addComponent(txtSueldo)
                                            .addComponent(txtFechaContratacion))))
                                .addGap(135, 135, 135)))
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegion)
                            .addComponent(txtNumero)
                            .addComponent(txtIdioma)
                            .addComponent(txtEmpresa)
                            .addComponent(txtEspecialidad)
                            .addComponent(txtExperiencia)
                            .addComponent(txtTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(58, 58, 58))))
            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelEmpleadosLayout.setVerticalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cmbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(jPanelEmpleadosLayout.createSequentialGroup()
                        .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtFechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("");
        btnAgregar.getAccessibleContext().setAccessibleName("btnAgregarEmpleado");
        jLabel4.getAccessibleContext().setAccessibleName("lbRut");

        tabPrincipal.addTab("Empleados", jPanelEmpleados);

        btnAgregarVehiculo.setText("Agregar vehiculo");
        btnAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVehiculoActionPerformed(evt);
            }
        });

        jLabel1.setText("Patente:");

        jLabel3.setText("Tipo:");

        jLabel12.setText("Capacidad:");

        javax.swing.GroupLayout jPanelVehiculoLayout = new javax.swing.GroupLayout(jPanelVehiculo);
        jPanelVehiculo.setLayout(jPanelVehiculoLayout);
        jPanelVehiculoLayout.setHorizontalGroup(
            jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehiculoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12))
                .addGap(76, 76, 76)
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPatente, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txtTipo)
                    .addComponent(txtCapacidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVehiculoLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(btnAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        jPanelVehiculoLayout.setVerticalGroup(
            jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVehiculoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnAgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Vehiculo", jPanelVehiculo);

        javax.swing.GroupLayout jPanelMostrarEntidadesLayout = new javax.swing.GroupLayout(jPanelMostrarEntidades);
        jPanelMostrarEntidades.setLayout(jPanelMostrarEntidadesLayout);
        jPanelMostrarEntidadesLayout.setHorizontalGroup(
            jPanelMostrarEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAreaResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        jPanelMostrarEntidadesLayout.setVerticalGroup(
            jPanelMostrarEntidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarEntidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAreaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPrincipal.addTab("Mostrar entidades", jPanelMostrarEntidades);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tabPrincipal)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabPrincipal.getAccessibleContext().setAccessibleName("Empleados");
        btnSalir.getAccessibleContext().setAccessibleName("Salir");
        btnSalir.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEmpleadoActionPerformed
        actualizarCampos();
    }//GEN-LAST:event_cmbTipoEmpleadoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    
    /**
    * Registra un nuevo vehículo utilizando
    * los datos ingresados en el formulario.
    *
    * @param evt evento generado por el botón.
    */
    private void btnAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVehiculoActionPerformed
        String patente = txtPatente.getText();
        String tipo = txtTipo.getText();
        String capacidad = txtCapacidad.getText();
        
        if(validarCamposVehiculo() ){
            Vehiculo vehiculo = new Vehiculo(
                patente,
                tipo,
                Integer.parseInt(capacidad));

            gestorEntidades.agregarEntidad(vehiculo);
            limpiarFormularioVehiculo();
            JOptionPane.showMessageDialog( this,"Vehiculo agregado correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarVehiculoActionPerformed
    
    /**
    * Actualiza el listado de entidades cuando
    * el usuario cambia a la pestaña correspondiente.
    *
    * @param evt evento de cambio de pestaña.
    */
    private void tabPrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPrincipalStateChanged
        
        if (tabPrincipal.getSelectedIndex() == 2) {
            txtAreaResultado.setText(gestorEntidades.mostrarEntidades());
        }
        int indice = tabPrincipal.getSelectedIndex();
        String titulo = tabPrincipal.getTitleAt(indice);
        //System.out.println("prueba"+titulo);
        if (titulo.equalsIgnoreCase("Mostrar entidades")) {
            txtAreaResultado.setText(gestorEntidades.mostrarEntidades());
        }
        txtAreaResultado.setText(gestorEntidades.mostrarEntidades());

    }//GEN-LAST:event_tabPrincipalStateChanged

    /**
    * Registra un nuevo empleado según el tipo
    * seleccionado en el formulario.
    *
    * @param evt evento generado por el botón.
    */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String tipoEmpleado = cmbTipoEmpleado.getSelectedItem().toString();
        String rut = txtRut.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String edad = txtEdad.getText();
        String calle = txtCalle.getText();
        String numero = txtNumero.getText();
        String ciudad = txtCiudad.getText();
        String region = txtRegion.getText();

        String sueldo = txtSueldo.getText();
        String fechaContratacion = txtFechaContratacion.getText();
        
        String idioma = txtIdioma.getText();
        String aniosExperiencia = txtExperiencia.getText();
        
        String empresa = txtEmpresa.getText();
        String especialidad = txtEspecialidad.getText();
        
        if(!validarCamposEmpleado(tipoEmpleado)){
            return;
        }
        
        Rut objRut = null;
        try {
            objRut = new Rut(rut);
        } catch (RutInvalidoException ex) {
            JOptionPane.showMessageDialog(this, "Formato no valido campo RUT.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        
        switch (tipoEmpleado) {
            case "Guia turistico":
                GuiaTuristico guiaTuristico = new GuiaTuristico(
                        idioma,
                        Integer.parseInt(aniosExperiencia),
                        objRut,
                        nombre,
                        telefono,
                        correo,
                        new Direccion(calle,Integer.parseInt(numero),ciudad,region),
                        Integer.parseInt(edad),
                        tipoEmpleado,
                        Double.parseDouble(sueldo),
                        fechaContratacion
                        
                );
                gestorEntidades.agregarEntidad(guiaTuristico);
                JOptionPane.showMessageDialog( this,"Guia turistico agregado correctamente.", "Info", JOptionPane.INFORMATION_MESSAGE);
                limpiarFormularioEmpleado();
                break;
            case "Colaborador externo":
                ColaboradorExterno colaboradorExterno = new ColaboradorExterno(
                        empresa,
                        especialidad,
                        objRut,
                        nombre,
                        telefono,
                        correo,
                        new Direccion(calle,Integer.parseInt(numero),ciudad,region),
                        Integer.parseInt(edad),
                        tipoEmpleado,
                        Double.parseDouble(sueldo),
                        fechaContratacion
                );
                gestorEntidades.agregarEntidad(colaboradorExterno);
                JOptionPane.showMessageDialog(this,"Colaborador externo agregado correctamente.");
                limpiarFormularioEmpleado();
                break;
            case "Recepcionista":
                
                Recepcionista recepcionista =
                        new Recepcionista(
                                txtTurno.getText(),
                                objRut,
                                nombre,
                                telefono,
                                correo,
                                new Direccion(calle,Integer.parseInt(numero),ciudad,region),
                                Integer.parseInt(edad),
                                tipoEmpleado,
                                Double.parseDouble(sueldo),
                                fechaContratacion);

                gestorEntidades.agregarEntidad(recepcionista);
                JOptionPane.showMessageDialog(this, "Recepcionista agregado correctamente.");
                limpiarFormularioEmpleado();
                break;
            default:
                break;
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(
            this,
            "Desea salir del sistema?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION
        );
    
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    /**
    * Valida los datos ingresados en el Formulario empleados
    * 
    * @return true si todos los datos son válidos;
    * false en caso contrario.
    */
    private boolean validarCamposEmpleado(String tipoEmpleado) {

        String rut = txtRut.getText();
        String nombre = txtNombre.getText();
        String telefono = txtTelefono.getText();
        String correo = txtCorreo.getText();
        String edad = txtEdad.getText();
        String calle = txtCalle.getText();
        String numero = txtNumero.getText();
        String ciudad = txtCiudad.getText();
        String region = txtRegion.getText();
        String sueldo = txtSueldo.getText();
        String fechaContratacion = txtFechaContratacion.getText();
        
        String idioma = txtIdioma.getText();
        String experiencia = txtExperiencia.getText();
        
        String empresa = txtEmpresa.getText();
        String especialidad = txtEspecialidad.getText();
        
        String turno = txtTurno.getText();

        if (validarParametro(rut)) {
            JOptionPane.showMessageDialog(this, "El campo RUT no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(nombre)) {
            JOptionPane.showMessageDialog(this, "El campo Nombre no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(telefono)) {
            JOptionPane.showMessageDialog(this, "El campo Teléfono no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(correo)) {
            JOptionPane.showMessageDialog(this, "El campo Correo no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(edad)) {
            JOptionPane.showMessageDialog(this, "El campo Edad no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(calle)) {
            JOptionPane.showMessageDialog(this, "El campo Calle no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(numero)) {
            JOptionPane.showMessageDialog(this, "El campo Número no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(ciudad)) {
            JOptionPane.showMessageDialog(this, "El campo Ciudad no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(region)) {
            JOptionPane.showMessageDialog(this, "El campo Región no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(sueldo)) {
            JOptionPane.showMessageDialog(this, "El campo Región no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
      
            return false;
        } else if (validarParametro(fechaContratacion)) {
            JOptionPane.showMessageDialog(this, "El campo Región no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        }
        
        if (!validarEnteroPositivo(
            txtEdad.getText(),
            "La edad debe ser un número entero positivo.")) {
            return false;
        }
        if (!validarEnteroPositivo(
            txtNumero.getText(),
            "El número de la dirección debe ser un número entero positivo.")) {
            return false;
        }
        
        
        if(tipoEmpleado.equals("Guia turistico")){
            if (validarParametro(idioma)) {
                JOptionPane.showMessageDialog(this, "El campo Idioma no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
                
                return false;
            } else if (validarParametro(experiencia)) {
                JOptionPane.showMessageDialog(this, "El campo Años de experiencia no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
                
                return false;
            }
            if (!validarEnteroPositivo(
                txtExperiencia.getText(),
                "Los años de experiencia deben ser un número entero positivo.")) {
                return false;
            }
        } else if (tipoEmpleado.equals("Colaborador externo")){
            if (validarParametro(empresa)) {
                JOptionPane.showMessageDialog(this, "El campo empresa no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
                
                return false;
            } else if (validarParametro(especialidad)) {
                JOptionPane.showMessageDialog(this, "El campo especialidad no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
                
                return false;
            }
        }else if(tipoEmpleado.equals("Recepcionista")){
            if(validarParametro(turno)){
                JOptionPane.showMessageDialog(this, "El campo turno no puede estar vacío.");
                return false;
            }
        }
        return true;
    }
    
    /**
    * Valida los datos ingresados para registrar
    * un vehículo.
    *
    * @return true si los datos son válidos;
    * false en caso contrario.
    */
    private boolean validarCamposVehiculo() {

        String patente = txtPatente.getText();
        String tipo = txtTipo.getText();
        String capacidad = txtCapacidad.getText();

        if (validarParametro(patente)) {
            JOptionPane.showMessageDialog(this, "El campo Patente no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(tipo)) {
            JOptionPane.showMessageDialog(this, "El campo Tipo de vehículo no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        } else if (validarParametro(capacidad)) {
            JOptionPane.showMessageDialog(this, "El campo Capacidad no puede estar vacío.", "Información", JOptionPane.INFORMATION_MESSAGE);
            
            return false;
        }else if (!validarEnteroPositivo(
            txtCapacidad.getText(),
            "La capacidad debe ser un número entero positivo.")) {
            return false;
        }

        return true;
    }
    
    /**
    * Verifica que un campo no se encuentre vacío.
    *
    * @param campo texto ingresado por el usuario.
    * @return true si el campo está vacío; false en caso contrario.
    */
    private Boolean validarParametro(String campo){
        Boolean resultado = false;
        if(campo.isBlank()){
            resultado = true;
        }
        return resultado;
    }
    
    /**
    * Valida que el valor ingresado corresponda
    * a un número entero positivo.
    *
    * @param valor texto ingresado.
    * @param mensaje mensaje mostrado si la validación falla.
    * @return true si el número es válido; false en caso contrario.
    */
    private boolean validarEnteroPositivo(String valor, String mensaje) {

        try {

            int numero = Integer.parseInt(valor);

            if (numero <= 0) {
                JOptionPane.showMessageDialog(
                       this,
                       mensaje,
                       "Información",
                       JOptionPane.INFORMATION_MESSAGE);
                return false;
            }

            return true;

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    mensaje,
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
    }
    
    /**
    * Habilita o deshabilita los campos según el tipo de entidad seleccionada.
    */
    /**
    * Habilita o deshabilita los campos del formulario
    * según el tipo de empleado seleccionado.
    */
    private void actualizarCampos() {

        String opcion = cmbTipoEmpleado.getSelectedItem().toString();

       
        if (opcion.equals("Guia turistico")) {

            txtIdioma.setEnabled(true);
            txtExperiencia.setEnabled(true);

            txtEmpresa.setEnabled(false);
            txtEspecialidad.setEnabled(false);

            txtTurno.setEnabled(false);

        }
        else if (opcion.equals("Colaborador externo")) {

            txtEmpresa.setEnabled(true);
            txtEspecialidad.setEnabled(true);

            txtIdioma.setEnabled(false);
            txtExperiencia.setEnabled(false);

            txtTurno.setEnabled(false);

        }
        else if (opcion.equals("Recepcionista")) {

            txtTurno.setEnabled(true);

            txtIdioma.setEnabled(false);
            txtExperiencia.setEnabled(false);

            txtEmpresa.setEnabled(false);
            txtEspecialidad.setEnabled(false);

        }
    }
   
    /**
    * Limpia todos los controles del formulario
    * de registro de empleados.
    */
    private void limpiarFormularioEmpleado() {
        txtRut.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtEdad.setText("");
        txtCalle.setText("");
        txtNumero.setText("");
        txtCiudad.setText("");
        txtRegion.setText("");
        txtSueldo.setText("");
        txtFechaContratacion.setText("");
        txtIdioma.setText("");
        txtExperiencia.setText("");
        txtEmpresa.setText("");
        txtEspecialidad.setText("");
        txtTurno.setText("");
    }
    
    /**
    * Limpia todos los controles del formulario
    * de registro de vehículos.
    */
    private void limpiarFormularioVehiculo() {
        txtPatente.setText("");
        txtTipo.setText("");
        txtCapacidad.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarVehiculo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelMostrarEntidades;
    private javax.swing.JPanel jPanelVehiculo;
    private javax.swing.JTabbedPane tabPrincipal;
    private java.awt.TextArea txtAreaResultado;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtFechaContratacion;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPatente;
    private javax.swing.JTextField txtRegion;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
